Repository geospoc/gqi-mapper-documentation, pull requests merged in 2021-08, with the labels that each got.

#93 chore: release v0.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: new release 🥳

#94 fix: correct url for hosting the static site
  .github/workflows/ci.yml
  nuxt.config.ts
Labels: bug 🐛, bugfix 🎾, github_actions

#95 chore: release v0.2.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: new release 🥳

#97 fix: issue of broken images links UA-238
  content/en/1.index.md
  nuxt.config.ts
  package-lock.json
  package.json
Labels: bug 🐛

#100 chore: release v0.3.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: new release 🥳

#102 feat: avail prod ready urls on home page UA-238
  content/en/1.index.md
Labels: enhancement 🎉
