Repository geospoc/gqi-mapper-documentation, pull requests merged in 2021-09, with the labels that each got.

#115 feat: update home page bullet links UA-238
  content/en/1.index.md
Labels: enhancement 🎉

#116 chore: pre–release v0.4.0 ✨
  .github/workflows/deploy-gh.yml
  .github/workflows/shipjs-trigger.yml
  content/en/1.index.md
  content/en/1.rural-school-mapping/1.about.md
  content/en/1.rural-school-mapping/2.objective.md
  content/en/1.rural-school-mapping/3.quick-start.md
  content/en/1.rural-school-mapping/4.results-portal.md
  content/en/1.rural-school-mapping/5.project-trials.md
  content/en/2.hospital-detection/1.data-pipeline-training-and-inference.md
  content/en/2.hospital-detection/2.geospatial-hospital-detection.md
  content/en/2.hospital-detection/3.input-data-files.md
  content/en/2.hospital-detection/4.model-weights.md
  docus.config.ts
  nuxt.config.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: dependencies 🤖, documentation 📙, enhancement 🎉, javascript

#117 chore: release v0.4.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: new release 🥳

#128 fix: use docus over docus app package UA-238
  docus.config.ts
  nuxt.config.ts
  package-lock.json
  package.json
Labels: bug 🐛, bugfix 🎾, enhancement 🎉
